package uk.ac.qub.agile.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import uk.ac.qub.agile.entry.SprintTeam;
import uk.ac.qub.agile.entry.SprintTeamExample;

public interface SprintTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    long countByExample(SprintTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int deleteByExample(SprintTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int insert(SprintTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int insertSelective(SprintTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    List<SprintTeam> selectByExample(SprintTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    SprintTeam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") SprintTeam record, @Param("example") SprintTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int updateByExample(@Param("record") SprintTeam record, @Param("example") SprintTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int updateByPrimaryKeySelective(SprintTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprintteam
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int updateByPrimaryKey(SprintTeam record);
}