package uk.ac.qub.agile.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import uk.ac.qub.agile.entry.Sprint;
import uk.ac.qub.agile.entry.SprintExample;

public interface SprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    long countByExample(SprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int deleteByExample(SprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int insert(Sprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int insertSelective(Sprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    List<Sprint> selectByExample(SprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    Sprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sprint record, @Param("example") SprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int updateByExample(@Param("record") Sprint record, @Param("example") SprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int updateByPrimaryKeySelective(Sprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sprint
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    int updateByPrimaryKey(Sprint record);
}