package uk.ac.qub.agile.entry;

public class Sprint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sprint.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sprint.sptintTitle
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String sptinttitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sprint.duration
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sprint.inProgress
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Boolean inprogress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sprint.blocked
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Boolean blocked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sprint.id
     *
     * @return the value of sprint.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sprint.id
     *
     * @param id the value for sprint.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sprint.sptintTitle
     *
     * @return the value of sprint.sptintTitle
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getSptinttitle() {
        return sptinttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sprint.sptintTitle
     *
     * @param sptinttitle the value for sprint.sptintTitle
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setSptinttitle(String sptinttitle) {
        this.sptinttitle = sptinttitle == null ? null : sptinttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sprint.duration
     *
     * @return the value of sprint.duration
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sprint.duration
     *
     * @param duration the value for sprint.duration
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sprint.inProgress
     *
     * @return the value of sprint.inProgress
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Boolean getInprogress() {
        return inprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sprint.inProgress
     *
     * @param inprogress the value for sprint.inProgress
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setInprogress(Boolean inprogress) {
        this.inprogress = inprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sprint.blocked
     *
     * @return the value of sprint.blocked
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Boolean getBlocked() {
        return blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sprint.blocked
     *
     * @param blocked the value for sprint.blocked
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }
}