package uk.ac.qub.agile.entry;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.title
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.inProgress
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Boolean inprogress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.blocked
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Boolean blocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.taskType
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String tasktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.duration
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.taskDetails
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String taskdetails;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.title
     *
     * @return the value of task.title
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.title
     *
     * @param title the value for task.title
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.inProgress
     *
     * @return the value of task.inProgress
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Boolean getInprogress() {
        return inprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.inProgress
     *
     * @param inprogress the value for task.inProgress
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setInprogress(Boolean inprogress) {
        this.inprogress = inprogress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.blocked
     *
     * @return the value of task.blocked
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Boolean getBlocked() {
        return blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.blocked
     *
     * @param blocked the value for task.blocked
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.taskType
     *
     * @return the value of task.taskType
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getTasktype() {
        return tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.taskType
     *
     * @param tasktype the value for task.taskType
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setTasktype(String tasktype) {
        this.tasktype = tasktype == null ? null : tasktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.duration
     *
     * @return the value of task.duration
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.duration
     *
     * @param duration the value for task.duration
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.taskDetails
     *
     * @return the value of task.taskDetails
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getTaskdetails() {
        return taskdetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.taskDetails
     *
     * @param taskdetails the value for task.taskDetails
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setTaskdetails(String taskdetails) {
        this.taskdetails = taskdetails == null ? null : taskdetails.trim();
    }
}