package uk.ac.qub.agile.entry;

public class UserStory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userstory.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userstory.projectID
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userstory.title
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userstory.description
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userstory.id
     *
     * @return the value of userstory.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userstory.id
     *
     * @param id the value for userstory.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userstory.projectID
     *
     * @return the value of userstory.projectID
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userstory.projectID
     *
     * @param projectid the value for userstory.projectID
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userstory.title
     *
     * @return the value of userstory.title
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userstory.title
     *
     * @param title the value for userstory.title
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userstory.description
     *
     * @return the value of userstory.description
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userstory.description
     *
     * @param description the value for userstory.description
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}