package uk.ac.qub.agile.entry;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.forname
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String forname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.surname
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.skills
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    private String skills;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.forname
     *
     * @return the value of user.forname
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getForname() {
        return forname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.forname
     *
     * @param forname the value for user.forname
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setForname(String forname) {
        this.forname = forname == null ? null : forname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.surname
     *
     * @return the value of user.surname
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.surname
     *
     * @param surname the value for user.surname
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setSurname(String surname) {
        this.surname = surname == null ? null : surname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.skills
     *
     * @return the value of user.skills
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public String getSkills() {
        return skills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.skills
     *
     * @param skills the value for user.skills
     *
     * @mbg.generated Sun Nov 15 21:28:18 CST 2020
     */
    public void setSkills(String skills) {
        this.skills = skills == null ? null : skills.trim();
    }
}